### ISSUE TITLE
Error including worker module

### ISSUE THREAD

**Issue by stodge** [eugeneware/workerjs#6]
If I pass the "true" option as the second option to the Worker, then I get an error while trying to import the worker.js file. This file is loaded locally, so the error is:

module.js:340
    throw err;
          ^
Error: Cannot find module './worker.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)

The code is:

var worker = new Worker('./worker.js', true);

Without the second parameter, the worker is successfully included.

Thanks

**Comment by stodge** [comment]
I guess it needs the absolute path when using this parameter.
